[phases.setup]
nixPkgs = ["...", "nodePackages.tailwindcss"]

[phases.build]
cmds = ["...", "make compile"]


[start]
runImage = '3.11-slim-bullseye'
onlyIncludeFiles = ['./', '/opt/venv']
cmd = "./start"
