[phases.setup]
nixPkgs = ["..."]


[phases.build]
cmds = [
  "...",
  "curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.4/tailwindcss-linux-x64",
  "chmod +x tailwindcss-linux-x64",
  "mv tailwindcss-linux-x64 ~/.local/bin/tailwindcss",
  "echo ${PATH}",
  "make compile",
]


[start]
cmd = "./start"
