[phases.setup]
nixPkgs = ["...", "nodePackages.tailwindcss"]

[phases.build]
cmds = ["...", "make compile"]


[start]
runImage = 'python:3.11-slim-bullseye'
onlyIncludeFiles = ['./', '/opt/venv']
cmd = "/opt/venv/bin/activate && ./start"
