[phases.setup]
nixPkgs = ["..."]


[phases.build]
cmds = [
  "...",
  # manually install the standalone tailwind standalone executable
  # this has a lot smaller footprint in the final build than using the nixpacks package
  # that pulls in a full node installation 
  "curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.4/tailwindcss-linux-x64",
  "chmod +x tailwindcss-linux-x64",
  "mv tailwindcss-linux-x64 /usr/bin/tailwindcss",
  "tailwindcss --help",
  "make compile",
]


[start]
cmd = "./start"
