#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset


# uvicorn app.main:app --port ${PORT} --host 0.0.0.0 --proxy-headers

gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:${PORT}