#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset


echo ${PATH}
source /opt/venv/bin/activate
echo ${PATH}
which python
uvicorn app.main:app --port ${PORT} --host 0.0.0.0 --proxy-headers